name: Quark签到

on:
  schedule:
    - cron: '0 1 * * *'   # 北京时间 09:00 (UTC+8 -> UTC+1)
    - cron: '0 5 * * *'   # 北京时间 13:00 (UTC+8 -> UTC+5)
  workflow_dispatch:      # 允许手动触发

jobs:
  check-if-already-signed:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
      already_signed: ${{ steps.check.outputs.already_signed }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 恢复签到成功记录缓存
        id: cache-success-restore
        uses: actions/cache@v4
        with:
          path: .last_success_date
          key: last-success-marker

      - name: 判断是否已签到
        id: check
        run: |
          current_date=$(TZ='Asia/Shanghai' date '+%Y-%m-%d')
          echo "当前北京时间: $current_date"

          if [ -f .last_success_date ]; then
            last_date=$(cat .last_success_date)
            echo "上次签到日期: $last_date"
            if [ "$last_date" = "$current_date" ]; then
              echo "今天已成功签到，跳过执行。"
              echo "skip=false" >> "$GITHUB_OUTPUT"
              echo "already_signed=true" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          fi

          echo "今天尚未签到，继续执行。"
          echo "skip=true" >> "$GITHUB_OUTPUT"
          echo "already_signed=false" >> "$GITHUB_OUTPUT"

      - name: Server 酱推送（已签到）
        if: steps.check.outputs.already_signed == 'true'
        env:
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
        run: |
          title="夸克网盘签到状态"
          content="今天（$(TZ='Asia/Shanghai' date '+%Y-%m-%d')）已成功签到，无需重复执行。"
          curl -X POST -d "text=$title&desp=$content" https://sctapi.ftqq.com/$SERVERCHAN_KEY.send

  sign-in:
    needs: check-if-already-signed
    if: needs.check-if-already-signed.outputs.skip == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 执行签到脚本并捕获结果
        env:
          COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
        id: sign_script
        run: |
          # 执行脚本并捕获所有输出（包括标准输出和错误输出）
          SIGN_OUTPUT=$(python checkIn_Quark.py 2>&1)
          echo "$SIGN_OUTPUT"
          # 将输出保存到环境变量（支持多行文本）
          echo "sign_result<<EOF" >> $GITHUB_ENV
          echo "$SIGN_OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 标记今天签到成功
        if: success()
        run: |
          date_str=$(TZ='Asia/Shanghai' date '+%Y-%m-%d')
          echo "$date_str" > .last_success_date
          echo "已记录成功签到日期: $date_str"

      - name: 保存成功记录到缓存
        if: success()
        uses: actions/cache@v4
        with:
          path: .last_success_date
          key: last-success-marker

      - name: Server 酱推送（签到成功）
        if: success()
        env:
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
        run: |
          title="夸克网盘签到成功"
          # 使用捕获的完整输出作为推送内容
          curl -X POST -d "text=$title" -d "desp=$sign_result" https://sctapi.ftqq.com/$SERVERCHAN_KEY.send

      - name: Server 酱推送（签到失败）
        if: failure()
        env:
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
        run: |
          title="夸克网盘签到失败"
          content="签到过程中发生错误，请检查脚本或Cookie是否过期。"
          curl -X POST -d "text=$title&desp=$content" https://sctapi.ftqq.com/$SERVERCHAN_KEY.send
